### ISSUE TITLE
Enable gh-pages

### ISSUE THREAD

**Issue by ccpandhare** [LakshSingla/frontend-101#1]
Hi! :-)
Glad to see that you started. Please enable gh-pages so that I can review.
Also when you're done wit something, make sure to move that to the "Done" section on [Projects/Assignment](https://github.com/LakshSingla/frontend-101/projects/1) from "To Do"

**Comment by LakshSingla** [comment]
Enabled the GitHub pages from master branch.

**Comment by ccpandhare** [comment]
Cool
