### ISSUE TITLE
Review of B1, B2, B3

### ISSUE THREAD

**Issue by ccpandhare** [LakshSingla/frontend-101#2]
🎉 
--
@LakshSingla 
B1, B2, B3 work as expected.
B1 ke sounds JS30 se liye the? xD
Anyways, I liked that you did focus on your styling. Some people would tend to leave out that part in the B series of sub assignments (@kunal-mohta :P)

**Comment by LakshSingla** [comment]
I picked the sounds from @kunal-mohta after asking him. All the sites were asking me to sign up :(

**Comment by kunal-mohta** [comment]
@ccpandhare 😮 😅
